removed 2nd confirmation for configuring oauth2

diff --git a/_scripts/reconfigure_oauth2 b/_scripts/reconfigure_oauth2
--- a/_scripts/reconfigure_oauth2
+++ b/_scripts/reconfigure_oauth2
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-## reconfigure_oauth2 VAR_PREFIX [default=yes|no]
+## reconfigure_oauth2 VAR_PREFIX
 
 ## If no default given, unconditionally set the Oauth2 environment variable VAR via wizard.
 ## If the default is given, the user will be asked if they want Oauth2 or not, defaulting to the yes or no supplied.
@@ -21,8 +21,6 @@ shift
 VAR_PREFIX=${1}
 shift
 
-DEFAULT=${1}
-
 enable_oauth2() {
     ${BIN}/reconfigure ${ENV_FILE} ${VAR_PREFIX}_OAUTH2=yes
 }
@@ -38,20 +36,9 @@ test -f ${ENV_FILE} || cp .env-dist ${ENV_FILE}
 
 CONTEXT_INSTANCE=$(basename $ENV_FILE | sed 's/.env_//')
 
-if [[ ${1} =~ ^default= ]]; then
-    DEFAULT_ENABLED_OAUTH2=no
-    if [[ ${1} =~ ^default=yes$ ]] || [[ $(${BIN}/dotenv -f ${ENV_FILE} get ${VAR_PREFIX}_OAUTH2) == "yes" ]]; then
-        DEFAULT_ENABLED_OAUTH2=yes
-    fi
-    echo 
-    echo "Using OpenID/OAuth2 will require a login to access your app. You can configure basic authorization by assigning an authorization group (authorization groups contain email addresses that are allowed to log into your app - you configure authorization groups by running \`make groups\` in the \`traefik\` directory)."
-    echo
+docker inspect traefik-forward-auth >/dev/null || (echo "traefik-forward-auth is not installed. Follow the directions at https://github.com/EnigmaCurry/d.rymcg.tech/tree/master/traefik-forward-auth#readme and then retry this" && exit 1)
 
-    ## Check if traefik-forward-auth is installed:
-    docker inspect traefik-forward-auth >/dev/null || (echo "traefik-forward-auth is not installed. Follow the directions at https://github.com/EnigmaCurry/d.rymcg.tech/tree/master/traefik-forward-auth#readme and then retry this" && exit 1)
 
-    ${BIN}/confirm ${DEFAULT_ENABLED_OAUTH2} "Do you want to enable OpenID/OAuth2" "?"  || disable_oauth2
-fi
 ## Update var in .env* file
 enable_oauth2
 
