Fix userns-remap

diff --git a/_scripts/userns-remap b/_scripts/userns-remap
--- a/_scripts/userns-remap
+++ b/_scripts/userns-remap
@@ -13,18 +13,20 @@ cmd=$1
 SSH_HOST=$(docker context inspect | jq -r ".[0].Endpoints.docker.Host" | sed 's|ssh://||g');
 SSH_UID=$(ssh ${SSH_HOST} id -u)
 [[ $SSH_UID != "0" ]] && SUDO_PREFIX="sudo" || SUDO_PREFIX=""
-DAEMON_CONF=${DAEMON_CONF:-/etc/docker/daemon.json}
+export DAEMON_CONF=${DAEMON_CONF:-/etc/docker/daemon.json}
 
 echo "## Checking Docker Daemon config (${DAEMON_CONF}) ..."
-ssh ${SSH_HOST} sh -c "test -f ${DAEMON_CONF} || ${SUDO_PREFIX} sh -c 'echo {} > ${DAEMON_CONF}'"
+if ! ssh ${SSH_HOST} "stat ${DAEMON_CONF} >/dev/null"; then
+    ssh ${SSH_HOST} "${SUDO_PREFIX} echo {} > ${DAEMON_CONF} && echo Created new ${DAEMON_CONF}"
+fi
 if [[ $cmd == "check" ]]; then
     # Just check for the setting, don't configure anything:
-    ssh ${SSH_HOST} "${SUDO_PREFIX} grep userns-remap ${DAEMON_CONF}" || echo "Not using userns-remap"
+    ssh ${SSH_HOST} "${SUDO_PREFIX} grep userns-remap ${DAEMON_CONF}" && echo "## userns-remap is configured" || echo "## userns-remap setting not found"
 else
     if ssh ${SSH_HOST} "${SUDO_PREFIX} grep userns-remap ${DAEMON_CONF}"; then
-        echo "${DAEMON_CONF} already has userns-remap setting."
+        echo "## ${DAEMON_CONF} already has userns-remap setting."
     else
-        echo "userns-remap setting not found"
+        echo "## userns-remap setting not found"
     fi
     if [[ $cmd == "true" ]]; then
         TMP_CONFIG=$(mktemp) && \
