Refactor wireguard container router for qBittorrent, Firefox, and Aria2 (#553)
* Adds Firefox

* add configs

* remove old aria configs

* standardize

* fix typos

* set a default admin credential

* minor README cleanup

* Set qbittorrent to bind to wireguard interface if container is installed to use wireguard

* Move a config to correct section

* Explain encoded default password

* add SessionInterfaceAddress

* remove aria2 references

* Adds categories

* Revert "Set qbittorrent to bind to wireguard interface if container is installed to use wireguard"

This reverts commit 5093f1f3808cd6af903d8e7304b607814f7f8117.

* Adds script that generates a killswich script for wireguard.

It outputs the script only, it does not run it.

* Changes copy-categories to build-hook-pre

* docker_subnets

* Add ipcalc requirement and ip address validators

* Arch linux reqs

* reconfigure_subnet reconfigure_ip_address

* kill switch

* wireguard static container ip address

* condense kill switch

* kill switch

* kill switch

* Remove example values and add instruction-comments

* Add healthcheck to kill/restart container when categories change

* wgnet

* Fix kill-switch recipe

* delete healthcheck for qbittorrent spurious from merge.

* container gets wireguard route

* wireguard ipv6

* ip masquerade rules

* firefox

* qbittorrent

* add kill switch to deny traffic to default docker gateway.

* firefox downloads volume

* remove broken killswitch that blocks traefik.

* firefox yt-dlp

* Fix regex

* Fix Regex

* centralize app-router-bootstrap-entrypoint.sh

* Fix default value

* firefox

* qbittorrent

* reconfigure_wireguard_instance default

* fix default

* fix default

* fix kill switch

* fix default

* fix entrypoint

* aria2 wireguard

* fix check_deps

* README

* README

* README

* README

* Add arg

* Simplify entrypoint.sh to always include args

* fix entrypoint

---------

Co-authored-by: Mike Wooskey <mike@thewooskeys.com>

diff --git a/wireguard/Makefile b/wireguard/Makefile
--- a/wireguard/Makefile
+++ b/wireguard/Makefile
@@ -5,7 +5,15 @@ include ${ROOT_DIR}/_scripts/Makefile.instance
 .PHONY: config-hook
 config-hook:
 	@${BIN}/reconfigure ${ENV_FILE} WIREGUARD_INSTANCE=${instance}
-
+	@echo
+	@echo "## It will be useful for the wireguard container to have a static IP address,"
+	@echo "## therefore you should create a unique subnet:"
+	@${BIN}/reconfigure_subnet ${ENV_FILE} WIREGUARD_DOCKER_SUBNET_IPV4 "Enter a unique IPv4 subnet CIDR for the wireguard network" "$$(${BIN}/docker_subnets propose)"
+	@${BIN}/reconfigure_subnet ${ENV_FILE} WIREGUARD_DOCKER_SUBNET_IPV6 "Enter a unique IPv6 subnet CIDR for the wireguard network" "$$(${BIN}/docker_subnets propose6)"
+	@${BIN}/reconfigure ${ENV_FILE} WIREGUARD_DOCKER_GATEWAY_ADDRESS_IPV4=$$(${BIN}/ip_from_minaddr $$(${BIN}/dotenv -f ${ENV_FILE} get WIREGUARD_DOCKER_SUBNET_IPV4) 1)
+	@${BIN}/reconfigure ${ENV_FILE} WIREGUARD_DOCKER_GATEWAY_ADDRESS_IPV6=$$(${BIN}/ip_from_minaddr_6 $$(${BIN}/dotenv -f ${ENV_FILE} get WIREGUARD_DOCKER_SUBNET_IPV6) 1)
+	@${BIN}/reconfigure ${ENV_FILE} WIREGUARD_DOCKER_WIREGUARD_ADDRESS_IPV4=$$(${BIN}/ip_from_minaddr $$(${BIN}/dotenv -f ${ENV_FILE} get WIREGUARD_DOCKER_SUBNET_IPV4) 2)
+	@${BIN}/reconfigure ${ENV_FILE} WIREGUARD_DOCKER_WIREGUARD_ADDRESS_IPV6=$$(${BIN}/ip_from_minaddr_6 $$(${BIN}/dotenv -f ${ENV_FILE} get WIREGUARD_DOCKER_SUBNET_IPV6) 2)
 	@echo ""
 	@echo "Enter the wireguard config values:"
 	@${BIN}/reconfigure_ask ${ENV_FILE} WIREGUARD_VPN_CLIENT_INTERFACE_PRIVATE_KEY "Enter the wireguard PrivateKey (ends with =)"
@@ -37,13 +45,37 @@ override-hook:
 ####                         # (this hardcodes the string into docker-compose.override.yaml)
 ####   name=@VARIABLE_NAME   # sets the template 'name' field to the literal string '${VARIABLE_NAME}'
 ####                         # (used for regular docker-compose expansion of env vars by name.)
-	@${BIN}/docker_compose_override ${ENV_FILE} project=:qbitorrent instance=@WIREGUARD_INSTANCE
+	@${BIN}/docker_compose_override ${ENV_FILE} project=:qbitorrent instance=@WIREGUARD_INSTANCE docker_subnet_ipv4=WIREGUARD_DOCKER_SUBNET_IPV4 docker_subnet_ipv6=WIREGUARD_DOCKER_SUBNET_IPV6 docker_gateway_address_ipv4=WIREGUARD_DOCKER_GATEWAY_ADDRESS_IPV4 docker_gateway_address_ipv6=WIREGUARD_DOCKER_GATEWAY_ADDRESS_IPV6 docker_wireguard_address_ipv4=WIREGUARD_DOCKER_WIREGUARD_ADDRESS_IPV4 docker_wireguard_address_ipv6=WIREGUARD_DOCKER_WIREGUARD_ADDRESS_IPV6
 
 
 .PHONY: install-hook
-install-hook:
-	@echo
+install-hook: wait kill-switch
+	@echo "## ✅ WireGuard service installed successfully"
 
 .PHONY: install-hook-pre
 install-hook-pre:
 	@echo
+
+.PHONY: kill-switch
+kill-switch:
+	@echo
+	@echo "## This script will install a systemd unit on the remote Docker HOST (${DOCKER_CONTEXT})."
+	@export DOCKER_CONTEXT=${DOCKER_CONTEXT}; \
+	if ${BIN}/confirm yes "Do you want to INSTALL the kill-switch for this WireGuard instance (${INSTANCE})" "?"; then \
+		if ! docker ps --format '{{.Names}}' | grep -qx 'wireguard_${INSTANCE}-wireguard-1'; then \
+			echo; \
+			echo "Error: WireGuard instance (${INSTANCE}) is not running." >/dev/stderr; \
+			echo; \
+			exit 1; \
+		fi; \
+		./wireguard-kill-switch-install.sh "${INSTANCE}"; \
+	else \
+		echo ""; \
+	fi
+
+.PHONY: kill-switch-uninstall
+kill-switch-uninstall:
+	@echo
+	@export DOCKER_CONTEXT=${DOCKER_CONTEXT}; \
+	${BIN}/confirm no "Do you want to REMOVE the kill-switch for this WireGuard instance (${INSTANCE})" "?"; \
+	./wireguard-kill-switch-install.sh --uninstall "${INSTANCE}"
